exploration plutonia experience
Citadel-Station-13/Citadel-Station-13-RP pull request #2331
Opened 2020-09-16 23:45 UTC by Hatterhat

## About The Pull Request
![image](https://user-images.githubusercontent.com/31829017/93403176-6392f600-f84c-11ea-8788-0076a2d8cf16.png)
## Why It's Good For The Game
if the pathfinder has a funny burst rifle there should be a mercenary equivalent
## Changelog
:cl:
add: Scarborough Arms has invested in higher-velocity 10mm rounds and given them to special units.
/:cl:

2020-09-17 00:16 UTC, lolman360 commented
new ballistic mobs: i sleep

2020-09-17 00:16 UTC, Hatterhat commented
they're hitscanners @lolman360

2020-09-17 00:17 UTC, lolman360 commented
yeha but haha funny 0.3 brutemod

anwyays add like, grenadier hivebots with projectile grenades
i want to see limbs get ripped off

2020-09-17 02:30 UTC, CharlesWedge commented
Dang it Hatter  I was working on a Merc PR too

2020-09-17 21:11 UTC, Zandario requested changes
Please balance this, no reason for smg-like weapon to be firing like a hitscan rifle

2020-09-17 21:11 UTC, Zandario commented on code/modules/projectiles/projectile/bullets.dm
> +	hitscan = TRUE
No reason for this to be hitscan.

2020-09-18 01:07 UTC, Hatterhat commented
pathfinders get a quirky burst rifle
this is my counterpoint

2020-09-18 01:37 UTC, CharlesWedge commented
That is not a good counterpoint Hatter, there is no reason to add hitscanners in. I have a merc PR in the works that will more than solve their current lack of firepower in  way that is fair and varied rather than hitscan.

2020-09-18 04:52 UTC, Hatterhat commented
dont get hitscanned lol

2020-09-19 03:46 UTC, Hatterhat commented
huh wow i really fucked up the branch pretty badly

2020-09-19 03:48 UTC, closed without merging