Adds an Age gate
Citadel-Station-13/Citadel-Station-13-RP pull request #2650
Opened 2021-01-24 17:06 UTC by buffyuwu

## Changelog
:cl:
add: Adds a one-time age gate for all users
server: adds logging via the client_prefs datum
/:cl:

https://i.imgur.com/f07Gq7S.jpg
![agegate1](https://user-images.githubusercontent.com/42501819/105637575-44c8ef80-5e3c-11eb-9483-c879abae21eb.JPG)
Prompt the user with an alert(), save to that client's data an age_verified value (via client.prefs) to keep track of who is verified

![agegate2](https://user-images.githubusercontent.com/42501819/105637576-44c8ef80-5e3c-11eb-839d-4241c37dc983.JPG)
Logout() and notify admins via message_admins + log_admin if they answer incorrectly

2021-01-24 18:10 UTC, timothyteakettle commented
I did this on main by banning anyone who failed it, but made it harder to accidentally fail by having them input their month and year (and if its ambiguous if they're 17 or 18, then it asks for day)

2021-01-24 18:19 UTC, buffyuwu commented
> I did this on main by banning anyone who failed it, but made it harder to accidentally fail by having them input their month and year (and if its ambiguous if they're 17 or 18, then it asks for day)

That would be super cool to have for RP! With this I want to get the ball rolling with the basic 18+ verification that all adult content providers use: the simple 'are you 18 or older' age verification before entering. I want to let this be a framework to get the ball rolling for a potentially prettier age gate in the future.

With this age gate, we can take steps to replace the archaic discord form application with an age verification system similar to what you made. Replacing the panic bunker/application process will allow for our playerbase to grow from it's stagnant low number, demonstrated very clearly from times where we had no panic bunker vs when we are using it a significant increase in population where that barrier is not present.

2021-02-10 07:36 UTC, Captain277 commented
Forgot this one was still up. Just gonna close this PR as post-testing period, community results regarding lifting the Panic Bunker were firmly in the negative.

2021-04-16 14:09 UTC, LetterN requested changes

2021-04-16 14:09 UTC, LetterN commented on code/modules/mob/new_player/new_player.dm
> +			Logout()
ban them?

2021-04-16 14:32 UTC, buffyuwu commented
re-opened amid maint discussions

2021-04-17 06:07 UTC, LetterN approved these changes
code good

2021-04-25 23:46 UTC, merged