Update jukebox.json
Citadel-Station-13/Citadel-Station-13-RP pull request #4663
Opened 2022-10-31 22:36 UTC by HenryTheCyborg

Gruppa Krovi fixed hopefully, added Cold Cold Cold, A Day in the Life, Kid Dynamo, First of the Gang to Die,

## About The Pull Request

just adding some more music to the jukebox. Gruppa Krovi fixed hopefully, added Cold Cold Cold, A Day in the Life, Kid Dynamo, First of the Gang to Die,

## Why It's Good For The Game

more songs for jukebox

## Changelog
:cl:
add: new songs to the jukebox
fix: fixed Gruppa Krovi, hopefully
soundadd: new songs to jukebox
/:cl:

2022-11-01 09:15 UTC, TheLordME approved these changes

2022-11-01 09:26 UTC, TheLordME requested changes

2022-11-01 09:26 UTC, TheLordME commented on config_static/jukebox.json
> +},
you need to get rid of the ,
json expects another song elsewise
```suggestion
}
```

2022-11-02 07:15 UTC, TheLordME commented
Hey there, if you don't mind, it would be nice if you'd join us on the Discord. We tend mostly help there with questions and ping you when we encounter issues with your PRs

2022-11-02 20:40 UTC, HenryTheCyborg commented
> Hey there, if you don't mind, it would be nice if you'd join us on the Discord. We tend mostly help there with questions and ping you when we encounter issues with your PRs

I'm already on the discord. I'm Kansan Gaming

2022-11-02 21:00 UTC, merged