fixes beakers eject when hands are full
Citadel-Station-13/Citadel-Station-13-RP pull request #4765
Opened 2022-11-24 13:55 UTC by silicons

2022-11-25 19:06 UTC, TheLordME requested changes

2022-11-25 19:06 UTC, TheLordME commented on code/game/machinery/_machinery.dm
> +		if(!user.put_in_hands(object))
Why not do the same as with the paper deletion?
```suggestion
		user.put_in_hands_or_drop(object))
```

2022-12-03 02:56 UTC, Zandario approved these changes

2022-12-03 22:42 UTC, TheLordME approved these changes

2022-12-03 22:43 UTC, merged