Adds More Guns to Armory & Removes Erroneous Holster Flag for Warden's Shotgun
Citadel-Station-13/Citadel-Station-13-RP pull request #4808
Opened 2022-12-07 07:39 UTC by Captain277

## About The Pull Request

1. **Adds Guns to Armory.**
2. **Removes Holster Flag from Warden's Shotgun.**

## Why It's Good For The Game

1. _Adds eight spare tasers and four more LTL gunboxes to the Armory._
3. _This is apparently my fault. It appears to have come over with the initial port, but it's possible I assigned the flag myself. Either way, it's not an intended feature and I'm surprised it took this long for anyone to mention it._

## Changelog

:cl:
add: Adds more guns to the Armory.
del: Removes Warden's Shotgun's holster flag.
/:cl:

2022-12-07 10:50 UTC, lunar-crater-ex commented
...okay, why does the already incredibly full and underused armory need More?

2022-12-07 12:26 UTC, Zandario commented on code/modules/projectiles/guns/projectile/shotgun.dm
> -	slot_flags = SLOT_BELT|SLOT_HOLSTER|SLOT_BACK
Did you mean to do this? Cause you have this PR: https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/4807/files

2022-12-07 12:33 UTC, Captain277 commented
> ...okay, why does the already incredibly full and underused armory need More?

Because this adds standard issue firearms. These guns were originally stocked in Security vendors which were readily available in the Security break room. I had an issue with that implementation, and always promised that the weapons would be moved to the Armory, rather than being put in an open vending machine.

It's been a few months due to conflicting map edits, but thanks to Map Merge I can finally return and fulfill that promise. The Armory is "incredibly full" of lethal weaponry for various situations, but it is understocked for day-to-day concerns like basic taser distribution and replacement.

2022-12-07 21:38 UTC, Shadowtail117 requested changes
Also, if you want to move security sidearms from the vendor to the armory, you may as well remove the .45 pistols from the SecTech as well. Alternatively put them in the officers' lockers so they don't need a warden/HOS to get their rubbers for them.

2022-12-07 21:38 UTC, Shadowtail117 commented on _maps/map_files/rift/rift-05-surface2.dmm
> +/obj/item/gunbox/lethal,
Your PR description says you want to add less-than-lethal boxes. If so, remove the `/lethal`:
```suggestion
/obj/item/gunbox{
	pixel_y = -4
	},
/obj/item/gunbox{
	pixel_y = 8
	},
/obj/item/gunbox{
	pixel_y = 4
	},
/obj/item/gunbox,
```

2022-12-17 12:51 UTC, silicons approved these changes
im just merging this because im redoing armory in a few weeks anyways

2022-12-17 12:51 UTC, merged