Dogborgs now CRUSH people's heads VERY RARELY when sharing a tile and resting.
Citadel-Station-13/Citadel-Station-13-RP pull request #5255
Opened 2023-03-29 18:52 UTC by nevimer

## About The Pull Request

![image](https://user-images.githubusercontent.com/77420409/228638715-dc067f1e-e12e-44bc-a270-0722cafd778d.png)
Bet
## Why It's Good For The Game

It'd probably be very rare and pretty funny ss13 soul to have incidents revolving around getting injured by machinery you climbed under. 

## Changelog

:cl:
add: Added a very small chance to have mechanical incidents with dogborgs. 
/:cl:

2023-03-29 20:58 UTC, Zandario requested changes
I'm not going to allow this in updateicon()

2023-03-29 23:08 UTC, nevimer commented
> I'm not going to allow this in updateicon()

I agree

2023-03-30 20:31 UTC, TheLordME approved these changes

2023-04-03 08:16 UTC, merged

2023-04-03 17:26 UTC, Lohikar commented
y'all know this was a shitpost PR, right