Adjusts the Connector Ports In Fighter Bays to Actually Connect
Citadel-Station-13/Citadel-Station-13-RP pull request #5365
Opened 2023-04-15 02:11 UTC by Captain277

## About The Pull Request

1. **Replaces Air Injectors in Fighter Bay and Hammerhead with Connectors.**

## Why It's Good For The Game

1. _The wrong connection type was mapped in. It was only reported to me today._

## Changelog

:cl:
fix: Corrects connector port type in fighter bay/Hammerhead.
/:cl:

2023-04-15 16:56 UTC, ktoma36 commented
Is going to conflict with #5361 cause I shifted the security hanger up a bit but I can solve the conflict on my end after this gets merged if you like :)
![image](https://user-images.githubusercontent.com/10539415/232239194-da48ebbf-3d26-4a20-85a8-58a190e64ed4.png)

2023-04-16 14:43 UTC, TheLordME requested changes

2023-04-16 14:43 UTC, TheLordME commented on maps/map_files/rift/rift-05-surface2.dmm
Multiple issues I have:
first one is of a logical/lore issue, on the pipe supplying the shuttle has no valves or anything preventing contaminated Air from leaking from the shuttle into whole station atmos, a simple pressure regulator would fix that.
number two, and I just realised that (but might be misremembereing), pipes leading onto shuttles do not properly seperate the pipe grid when the shuttle leaves, meaning you can pump gases to a ship anywhere on the overmap.
Just add a pump from the connector with the Air cannister on the shuttle to empty the cannister into the pressure tank and a connector port outside where you can refill the cannister directly

2023-04-17 07:38 UTC, Captain277 commented
> Is going to conflict with #5361 cause I shifted the security hanger up a bit but I can solve the conflict on my end after yours gets merged if you like :) ![image](https://user-images.githubusercontent.com/10539415/232239194-da48ebbf-3d26-4a20-85a8-58a190e64ed4.png)

Go ahead with yours first fam. This is a pretty low priority change so it can wait! :)

2023-04-26 05:21 UTC, closed without merging