Fighter landing mode
Citadel-Station-13/Citadel-Station-13-RP pull request #5572
Opened 2023-06-05 14:19 UTC by MonaraMir

## About The Pull Request
adds a landing mode to fighters

## Why It's Good For The Game
space-only fighters cannot land correctly, or have on-station maintenance performed efficiently

coded from my phone please triple check <3

2023-06-05 22:52 UTC, ktoma36 approved these changes

2023-06-05 23:06 UTC, ktoma36 approved these changes

2023-06-07 20:15 UTC, TheLordME requested changes

2023-06-07 20:15 UTC, TheLordME commented on code/game/mecha/combat/fighter.dm
> +		step_in = 10 //Slow now that they're on landing gear
as far as I can tell you are not restoring the previous step_in, so once they were on landing gear they can never regain their original speed

2023-06-08 17:30 UTC, TheLordME approved these changes

2023-06-09 01:07 UTC, MonaraMir commented
ready for fullmerge

2023-06-09 01:37 UTC, ktoma36 submitted a review, later dismissed

2023-06-09 05:33 UTC, MonaraMir commented
MERGE #5584 WITH THIS PR

2023-06-09 06:11 UTC, silicons approved these changes

2023-06-09 06:11 UTC, merged