Cryptominer now accepts Helium, Vimur and phoron
Citadel-Station-13/Citadel-Station-13-RP pull request #5904
Opened 2023-08-22 20:34 UTC by TheLordME

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
tweak: Cryptominer now accepts Helium, Vimur and phoron
/:cl:

2023-08-22 21:45 UTC, BlueWildrose requested changes
Typo.

2023-08-22 21:45 UTC, BlueWildrose commented on code/modules/power/crypto_miner.dm
> +    . += "An indicator on [src]'s controll panel indicates that [src] is in a [(check_right_atmos() ? "sufficent" : "insufficent")] amount of helium, vimur or phoron to function."
```suggestion
    . += "An indicator on [src]'s control panel indicates that [src] is in a [(check_right_atmos() ? "sufficent" : "insufficent")] amount of helium, vimur or phoron to function."
```
Should fix  your typo while we're here

2023-08-23 04:50 UTC, silicons approved these changes

2023-08-24 08:12 UTC, Captain277 approved these changes

2023-08-26 05:49 UTC, merged