Let Slip the Dogs of War
Citadel-Station-13/Citadel-Station-13-RP pull request #5905
Opened 2023-08-22 23:02 UTC by CharlesWedge

## The Machines Rise
With the recent sector wide hack rogue synthetics have become a problem in the sector. What's worse now corrupted fabricators are even building more combat designs! With an increasingly dangerous galaxy, it seems that mercenaries will not be the only threat brave explorers and security teams may face today. All security forces are advised to stay on the lookout for the latest threat to the galaxy, and those not equipped to take them on are advised, stay well out range!

## Why It's Good For The Game
As we want to move away for humanoid threats for simple mobs, I feel it necessary to shore up killer machines as more advanced type of enemy to take the place of humans in terms of  'dangerous opponents'. The current selection of machines mobs tend to be more niche in function (we can't exactly use the nanite horror as common enemies). Also there is a bigger maint drone now because the smaller ones weren't bad enough, least these ones are easier to hit.

## Changelog

:cl:
add: 4 New Hostile Drones, Three Dogs (including one sniper), and a Maint Drone.
add: New News article elaborating on recent events.
tweak: drones are now part of the same faction as hivebots. This means evil bots will now cooperate (Hivebots are being updated next).
/:cl:

2023-08-23 03:28 UTC, BlueWildrose requested changes
Some proofreading for you.

2023-08-23 03:28 UTC, BlueWildrose commented on code/modules/lore_codex/news_data/main.dm
> +	be infected by  a malignant virus that was spread across the sector through subspace relays. Subverted silicons from the simplest drone to ship AIs were driven to stockpile materials \
```suggestion
	be infected by a malignant virus that was spread across the sector through subspace relays. Subverted silicons from the simplest drone to ship AIs were driven to stockpile materials \
```

2023-08-23 03:28 UTC, BlueWildrose commented on code/modules/lore_codex/news_data/main.dm
> +	for an as of yet unreleashed line of Hephaestus combat drones! These 'Warhound' series combat drones are armed with a variety od powerful mounted weapons meant to make short work \
```suggestion
	for an as of yet unreleased line of Hephaestus combat drones! These 'Warhound' series combat drones are armed with a variety of powerful mounted weapons meant to make short work \
```

2023-08-23 03:28 UTC, BlueWildrose commented on code/modules/mob/living/simple_mob/subtypes/mechanical/corrupt_maint_drone_vr.dm
> +	Now this drone seems to target any organic life it comes across, working with others of its kind to overwhealm \
```suggestion
	Now this drone seems to target any organic life it comes across, working with others of its kind to overwhelm \
```

2023-08-23 03:28 UTC, BlueWildrose commented on code/modules/mob/living/simple_mob/subtypes/mechanical/corrupt_maint_drone_vr.dm
> +	Larger foes, if one is found, a swarm of others are not too far away.\
```suggestion
	larger foes. If one is found, a swarm of others are not too far away.\
```
If this is part of the same sentence, remove the capitalization.

2023-08-24 03:54 UTC, Captain277 approved these changes

2023-08-24 03:54 UTC, merged