Caliber updates
Citadel-Station-13/Citadel-Station-13-RP pull request #5941
Opened 2023-09-02 16:27 UTC by GySgtMurphy

## About The Pull Request
 
Changing some Russian specific calibers out for more appropriate ones

## Why It's Good For The Game

Fewer /k/ memes from 20 years ago would be nice

## Changelog

:cl:

tweak: tweaked a few things, name wise

/:cl:

2023-09-03 00:50 UTC, yourdoom9898 commented
I'm going to be honest, I really don't see the point in changing the names of one intermediate rifle cartridge to another intermediate rifle cartridge. Just seems like a bunch of typepath changing 4noraisin.

2023-09-03 18:35 UTC, GySgtMurphy commented
> I'm going to be honest, I really don't see the point in changing the names of one intermediate rifle cartridge to another intermediate rifle cartridge. Just seems like a bunch of typepath changing 4noraisin.

This is something that has been in discussion for a while, and it's a good way for me to learn how PRs are made, pushed, and fix some things I've not liked with names for quite a while.

2023-09-03 21:46 UTC, Captain277 requested changes
I wondered how you hadn't run into map compiling issues, and I've noticed that you didn't correctly repath the actual magazine strings. For instance, the (formerly) 5.45 magazine has been renamed to magazine (5.56mm), but its path is still m545. You need to change the path names too. However, when you do this, it will throw up a ton of map errors where m545 instances have been hard mapped in - as m545 will stop existing. You have to go in and manually replace those missing instances with the new m556 path. If you're comfortable doing this, you should do it before this is merged. But mapping is complex. If you aren't, I can come in and do the repathing and push it to your branch. Let me know.

2023-09-10 22:21 UTC, Captain277 approved these changes

2023-09-10 22:21 UTC, merged