Adds explosive collars
Citadel-Station-13/Citadel-Station-13-RP pull request #5960
Opened 2023-09-09 18:57 UTC by DiscordWizard

## About The Pull Request

Adds a copy of a shock collar which is explosive instead, because I didn't want to copy so much code

## Why It's Good For The Game

Well we didn't have explosive collars and I liked the idea of having something more _encouraging_ for my xenochimera character rather than a button that just makes them more prone to acting like an animal

Feel free to tell me to be less lazy with the code or remove it from the loadout section, I felt like it could be used for whatever people may need it, private or event wise

## Changelog

:cl:
add: Added explosive collars
/:cl:

2023-09-10 21:29 UTC, silicons requested changes
we're not nearly dystopian enough that i want literal bomb collars in the loadout

2023-09-10 22:25 UTC, Captain277 commented
> we're not nearly dystopian enough that i want literal bomb collars in the loadout

It's kinda hot though...

2023-09-11 15:37 UTC, DiscordWizard commented
> we're not nearly dystopian enough that i want literal bomb collars in the loadout
I could put it on the xenowear section restricted to xenochimera if you want, It's the only character I wanted to use it on

2023-09-17 07:48 UTC, BlueWildrose requested changes
Pretty sure getting your head blown off wouldn't exactly be _electrocution_.

2023-09-17 07:48 UTC, BlueWildrose commented on code/modules/clothing/under/accessories/accessory.dm
> +			M.apply_damage(220, BRUTE, "head", used_weapon="Electrocution")
```suggestion
			M.apply_damage(60, BURN, "head", used_weapon="Bomb Collar")
			M.apply_damage(220, BRUTE, "head", used_weapon="Bomb Collar")
```

2023-09-19 02:45 UTC, silicons commented
feel free to reopen if you want this as a feature without a loadout entry

2023-09-19 02:45 UTC, closed without merging