Fixes Engineers being unable to select pleated skirts
Citadel-Station-13/Citadel-Station-13-RP pull request #5963
Opened 2023-09-10 18:17 UTC by LordPapalus

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
fix: removes atmospheric technician and chief engineer access limit on pleated skirts
/:cl:

2023-09-11 19:22 UTC, ktoma36 approved these changes

2023-09-12 20:07 UTC, TheLordME requested changes

2023-09-12 20:07 UTC, TheLordME commented on code/modules/loadout/loadout_role_restricted.dm
> -	allowed_roles = list("Chief Engineer", "Atmospheric Techician")
please dont remove the allowed roles and keep it in restricted, either move it to the unrestricted section, or change the line to allowed_roles = list("Chief Engineer", "Atmospheric Technician", "Station Engineer", "Senior Engineer")

2023-09-13 18:30 UTC, TheLordME approved these changes

2023-09-13 18:30 UTC, merged