Adds an Invisible Satchel for Aesthetics
Citadel-Station-13/Citadel-Station-13-RP pull request #6040
Opened 2023-10-01 18:25 UTC by Captain277

## About The Pull Request

1. **Adds an 'Invsible' Satchel Type.**

## Why It's Good For The Game

1. _Backpacks are really useful, but sometimes you don't want them covering up your whole outfit and stuff. This adds a new invisible satchel type that lets you show off your costumes without sacrificing storage._

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
tweak: tweaked a few things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-10-04 07:22 UTC, TheLordME approved these changes

2023-10-04 07:22 UTC, TheLordME commented on code/modules/preferences/preference_setup/general/04_equipment.dm
>  	// TODO - Looks like this is duplicating the work of sanitize_character() if so, remove
have you checked this?

2023-10-04 08:25 UTC, TheLordME submitted a review, later dismissed

2023-10-04 19:07 UTC, silicons requested changes
loadout only on seasonal events please

2023-10-09 06:26 UTC, silicons submitted a review, later dismissed

2023-10-09 06:30 UTC, silicons approved these changes

2023-10-10 09:47 UTC, merged