Removes redundant and misleading alt-titles, adds title_blurbs to a lot that remain, adds one or two more alt-titles
Citadel-Station-13/Citadel-Station-13-RP pull request #6056
Opened 2023-10-05 18:07 UTC by SingingSpock

## About The Pull Request

Trims out a handful of alt-titles that were misleading and/or redundant, and adds title_blurb text where missing to most of the ones that remain in files I touched, to help establish what each alt-title is for. (I then realized that nothing shows the title_blurb in-game, but that's a problem for another PR). The departmental senior titles were also given a desc that indicates their actual role in our current SOP (including Senior Researcher, whose desc was previously literally "Lorem Ipsum." There's also a couple alt-titles, most notably Trainee EMT, since there wasn't a good role for that previously. Exact details of the changes are too long to put in here, but it's pretty easily readable. The most significant alteration was changing almost all the titles for the senior medical position, removing "Head Nurse" (because that makes no sense whatsoever as a role of authority that doctors would look towards for advice) and making "Senior Physician" the primary title.

## Why It's Good For The Game

Alt-titles were often just a dozen ways to say kinda the same thing. In the worst cases, they were actively confusing (e.g. Counselor as an alt-title for both Chaplain and Psychiatrist) or not indicative at all of the original job (e.g. Director of Operations for Captain). This leaves each alt-title in non-service departments having a distinct role that they fill, indicated by title_blurb text (which I will work on fixing next since I noticed it isn't actually shown in-game). Additionally, a couple of niches weren't previously covered by alt-titles (such as Trainee EMT), so those were added.

## Changelog

:cl: SingingSpock
tweak: Alt-titles were trimmed down and more description given to many remaining ones. A couple more were added.
/:cl:

2023-10-05 18:29 UTC, SingingSpock commented
I don't know why the linter is still complaining, I re-added the trailing newlines to those files

2023-10-08 15:25 UTC, timothyteakettle requested changes

2023-10-08 15:25 UTC, timothyteakettle commented on code/modules/jobs/job_types/station/security/detective.dm
> +
this is not an empty newline

2023-10-08 15:25 UTC, timothyteakettle commented on code/modules/jobs/job_types/station/science/senior_researcher.dm
> +
this is also not an empty newline

2023-10-08 22:31 UTC, silicons requested changes
blah blah subjective nitpicks

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/command/head_of_personnel.dm
> +		"First Officer" = /datum/prototype/struct/alt_title/fo,
don't remove CRO

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/engineering/senior_engineer.dm
> -	background_enforce = TRUE
don't remove this without checking with lore people

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/engineering/station_engineer.dm
> +	title = "Engineer"
i don't really see the need to shorten this to engineer

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/engineering/station_engineer.dm
> -	background_enforce = TRUE
don't remove these without asking lore people

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/chemist.dm
> -
don't remove this without checking with lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/head_nurse.dm
> -	background_enforce = TRUE
dont remove this without checking with lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/medical_doctor.dm
> -		"Medical Intern" = /datum/prototype/struct/alt_title/doctor/intern,
don't remove this; much like we have cadet vs jr officer

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/medical_doctor.dm
dont remove this without checking with lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/paramedic.dm
> -	background_enforce = TRUE
dont remove this without checking with lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/paramedic.dm
> +		"Trainee Emergency Medical Technician" = /datum/prototype/struct/alt_title/emt_trainee
way too wordy; a trainee should just be intern

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/medical/psychiatrist.dm
> -		"Therapist" = /datum/prototype/struct/alt_title/therapist
curious
why are we removing therapist but adding counselor

latter sounds even less like a proper medical role

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/science/roboticist.dm
> -
blah blah lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/science/roboticist.dm
> +		"Mechatronic Technician" = /datum/prototype/struct/alt_title/mech_tech
engineer sounds cooler for both tbh; why are we changing it?

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/security/warden.dm
> +		"Brig Overseer" = /datum/prototype/struct/alt_title/warden/overseer,
ngl this is such a silly title but whatever idc

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/supply/cargo_technician.dm
> -
blah blah lore

2023-10-08 22:31 UTC, silicons commented on code/modules/jobs/job_types/station/supply/quartermaster.dm
> -		"Logisticai-Adept" = /datum/prototype/struct/alt_title/logisticai_adept
blah blah lore

2023-10-12 05:07 UTC, BlueWildrose reviewed
Also, it'd be neat if the shaft miner had some alt titles to do with salvaging. Chances are that might become their default titles eventually anyways.
Salvage Technician, Salvage Specialist, or something. Maybe both.

2023-10-13 12:20 UTC, silicons approved these changes

2023-10-13 12:20 UTC, silicons commented
@timothyteakettle

2023-10-20 09:01 UTC, merged