protean blob chameleon clothing
Citadel-Station-13/Citadel-Station-13-RP pull request #6261
Opened 2024-01-08 12:06 UTC by lolman360

fetish code

2024-01-10 21:00 UTC, TheLordME requested changes

2024-01-10 21:00 UTC, TheLordME commented on code/modules/hardsuits/suits/species/protean.dm
very important change

2024-01-16 20:44 UTC, TheLordME approved these changes

2024-01-17 22:30 UTC, timothyteakettle commented on code/modules/mob/holder.dm
> +
is there a reason we have 4 newlines here

2024-01-17 22:30 UTC, timothyteakettle commented on code/modules/species/protean/protean_blob.dm
> +
you dont need 2 newlines here

2024-01-17 22:32 UTC, timothyteakettle commented
other than an excessive use of newlines this is fine

2024-01-18 11:26 UTC, timothyteakettle approved these changes

2024-01-18 11:27 UTC, merged