Atlas Genpop [Do not Merge]
Citadel-Station-13/Citadel-Station-13-RP pull request #6339
Opened 2024-03-15 08:36 UTC by MonaraMir

## About The Pull Request

Removes isolation cells with timers on them, replaces them with a genpop system. This PR only affects Rift(atlas).

## Why It's Good For The Game

GBJ is awful, especially when security is the one doing it to you. This will also make it easier to get event roles to play, since they wont be forced into the youtube cells to afk the rest of the round away.

Yes, there are still ways to isolate prisoners if they are attacking each other in prison, but it should hopefully be used as a last resort only.

## Changelog

:cl:
add: Refurbished Genpop, and put turnstiles and prisoner lockers into effect on Atlas.
del: Deleted old timed cells on Atlas
/:cl:

2024-03-16 00:09 UTC, MonaraMir commented
Ready for review, but cannot be merged until Prisoner IDs have their access fixed. Bug report is in maintainer triage.

2024-03-16 01:02 UTC, MonaraMir commented
I suck at figuring out why my PRs wont compile when committing, but it'll compile fine on my machine. If any reviewer actually sees a problem, let me know. Else idk, shove it in anyways. Works on my machine. 👍

2024-03-17 17:07 UTC, MonaraMir commented
Ready for testmerge once #6346 is testmerged.

2024-03-18 21:09 UTC, TheLordME requested changes

2024-03-18 21:09 UTC, TheLordME commented on code/game/area/Space Station 13 areas.dm
you said you would move the /area/security to a seperate file

2024-03-18 21:46 UTC, MonaraMir commented on code/game/area/Space Station 13 areas.dm
I forgor

2024-03-20 23:37 UTC, silicons approved these changes

2024-03-21 00:02 UTC, merged