genpop QOL updates
Citadel-Station-13/Citadel-Station-13-RP pull request #6359
Opened 2024-03-26 20:38 UTC by MonaraMir

Fixes a disposal chute in processing.

Localized entirely within genpop:

Removes airlock next to genpop watchtower.
Adds more fire extinguishers/alarms.
Fixes some spline.
Adds cards/dice to table.
Adds 2 sets of vent/scrubbers to top floor and bottom floor, one per.
Replaced glass cell doors with solid steel.

2024-03-28 11:31 UTC, TheLordME requested changes

2024-03-28 11:31 UTC, TheLordME commented on maps/rift/levels/rift-03-underground1.dmm
The lower part should have a lot more vents and scrubbers

2024-03-30 01:51 UTC, MonaraMir commented on maps/rift/levels/rift-03-underground1.dmm
Added 2 more sets to the lower part

2024-03-30 13:10 UTC, TheLordME approved these changes

2024-03-30 13:20 UTC, merged