promethean number tweaks
Citadel-Station-13/Citadel-Station-13-RP pull request #6416
Opened 2024-04-26 10:36 UTC by bearrrrrrrr

## About The Pull Request

1. removes the inexplicable speed increase and item slowdown...not-decrease, from prommies
2. nerfs their limb hp **(literally arbitrary values picked for rn til people come up with a comfy number, i think 25 feels good and hits a good threshhold but who knows)**

## Why It's Good For The Game

already spent a long time talking on discord about this but the tl;dr is that promethean is a really, really strong species at base, and has the added benefit of not suffering from baymed. 

event managers have expressed a bit of frustration at how strong the species is and i also agree w/ it. this is what was eventually settled on, while people work on adding other stuff to them in the background. (i think them having pain would also be cool since they're literally a fully biological species but that is neither here nor there, and it may be unironically rather crippling)

this won't really 'fix' it but it's a good start

## Changelog

:cl:
balance: promethean number tweaks - removes random free speed buffs (almost half as fast as a taj bonus??) and decreases limb splodey threshhold
/:cl:

2024-04-26 10:37 UTC, bearrrrrrrr commented
again, literally an arbitrary value picked for rn (reverted to what it previously was), waiting on response from folks on what might feel like a good spot

2024-04-27 03:45 UTC, BlueWildrose requested changes
As discussed in Discord, having it be 25 is probably best. It still is enough damage to cause instant limb break by a laser if a prommie has about 40% armor.

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 03:45 UTC, BlueWildrose commented on code/modules/organs/external/species/slime.dm
> +	max_damage = 20
```suggestion
	max_damage = 25
```

2024-04-27 16:11 UTC, BlueWildrose approved these changes

2024-04-28 00:23 UTC, timothyteakettle commented
i'm pretty fine with these changes

2024-05-01 10:20 UTC, merged