Bugfix /obj/structure/closet close() and open() icon issue
Citadel-Station-13/Citadel-Station-13-RP pull request #6420
Opened 2024-04-30 04:05 UTC by Sorrowfulwinds

## About The Pull Request
Fixes bug where calling open() or close() on a /obj/structure/closet wouldn't update the icon.

## Why It's Good For The Game
Fundamental procs should not need additional code to work.

## Changelog
-Adds update_icon() to close() and open()
-Removes update_icon() from toggle() as it just calls close() and open()

:cl: Shadowcat
fix: Fix crate open and close procs not updating the icon on the crate.
/:cl:

2024-05-01 10:14 UTC, TheLordME approved these changes

2024-05-01 20:32 UTC, Putnam3145 commented
Crates don't have proper states set, so this breaks all crates.

2024-05-02 06:37 UTC, TheLordME requested changes
as putnam pointed out, update icon does not set the right icon states
for crates its initial(icon_state) + "closed" 
With no spaces in the string

2024-05-23 06:24 UTC, TheLordME approved these changes

2024-05-23 06:24 UTC, TheLordME approved these changes
Checksout locally

2024-05-23 09:35 UTC, merged