factions cleanup - removes most factions from station
Citadel-Station-13/Citadel-Station-13-RP pull request #6531
Opened 2024-06-19 14:10 UTC by silicons

as discussed in suggestions on discord (thread was left up for days)

tldr for those git trawling in a few months:

it's nonsensical to maintain a dozen factions rather than focus on the dynamics of NT letting on a select few
we want to shift towards a secure research ship, it doesn't make sense to have everyone clown car-ing in from every different faction without strong ties to NT or other IC reason for them to be there.

2024-06-20 06:43 UTC, lolman360 commented
good pr

2024-06-20 17:01 UTC, BlueWildrose commented on code/modules/lore_hardcoded/faction.dm
>  	job_whitelist = list(
I noticed the FTU lacks the trader job. Wouldn't this lock them out of being the main faction that is traders to begin with?

2024-06-22 19:13 UTC, TheLordME requested changes
Comments are **not** a storage for old code

2024-06-23 21:56 UTC, TheLordME submitted a review, later dismissed

2024-06-24 09:25 UTC, TheLordME approved these changes

2024-06-24 09:25 UTC, merged