[WIP] Gives Station access to silver ammunition.
Citadel-Station-13/Citadel-Station-13-RP pull request #6781
Opened 2024-10-01 02:43 UTC by AlphaM01

## About The Pull Request
You'd think from the title that this is a 2-line PR, but I've actually coded + sprited silver versions of a few common magazines that used not to have them, fixed a bunch of bugs and inconsistencies, and so on.

## Why It's Good For The Game
Silver bullets have historically been an adminspawn thing that's never used. Considering lore has been moving in the direction of plain silver not being the end-all-be-all against the supernatural, it might be nice to give players the option to actually use specialized ammo, after all, printing a bullet out of X or Y metal isn't exactly difficult.
To reflect this, the description HAS been changed to no longer say these are blessed or anything of the sort. The door remains open for a more specialized non-mass-producible Holy Silver variant if that becomes necessary.

## Known Issues
Autolathe is currently not accounting for the silver (or any) material cost for most of these for an unknown reason.
All .357 speedloader sprites do not update for an unknown reason.

## Changelog

:cl:
add: Added several types of printable silver bullet clips and magazines to the autolathe.
add: Added several sprites to support the new magazines.
tweak: shortened and fixed most silver bullet descriptions.
tweak: all silver projectiles standardized to work against MOB_CLASS_DEMONIC & MOB_CLASS_ABERRATION.
tweak: removed a couple instances of xenomorphs using MOB_CLASS_ABERRATION.
fix: .44 rubber magazine now specifies it's loaded with rubber on the name.
fix: fixed .44 rubber magazine no longer prints preloaded with lethals.
fix: small silver bullets (such as .38 and 9mm) no longer invisible.
/:cl:

2024-10-01 02:53 UTC, Shadowtail117 requested changes

2024-10-01 02:53 UTC, Shadowtail117 commented on code/datums/design/designs/ammo/shotgun.dm
> +	/datum/design/ammo/shotgun/clip/dual/silver
```suggestion
/datum/design/ammo/shotgun/clip/dual/silver
```

Needs to be unindented

2024-10-07 20:47 UTC, AlphaM01 commented
Waiting only on .357 speedloader fixes and Autolathe material cost changes.

2024-10-26 06:47 UTC, silicons approved these changes

2024-10-26 06:48 UTC, merged