Halloween Week 2: Ghosts in the Geiger Counter
Citadel-Station-13/Citadel-Station-13-RP pull request #6785
Opened 2024-10-03 20:42 UTC by CharlesWedge

## You should probably equip a radsuit.
Adds 4 new spooky creatures, 2 of which emit radiation passively creating a new type of hazard around dealing with them. A short description of the new spooks are as follows:

_**Gammawraith:**_ Resembling a specter wearing a radiation suit. The gamma wraith passively emits a small amount of radiation while firing armor-piercing gamma beams that irradiate the target.
_**Charred Runner:**_ A burnt corpse that runs at its enemies, a glass canon. Very resistant to energy weapons.
**_Burning Runner:_** A extremely fast enemy resembling a burning corpse whose attack sets targets. Almost immune to burn weapons.
**_Demoncore:_** Inflicts death by floating slowly at its enemies and giving them radiation poisoning.

## Enemy Variety
The new mobs provided at least some variety to the existing spooks being distinctively not blood cult themed monsters. In addition, many are dangerous in ways other hostiles simply aren't. The demon core emits radiation which can quickly kill the unprepared (slowly and agonizingly), while the gamma wraith can chip through any armor. The burning and charred also use energy weapon resistance to force melee or bullet combat. The burning specifically is meant to cause chaos by lighting those caught by it on fire (and is fast enough its very hard to kite).

## Changelog

:cl:
add: Four new spooks, ready for Halloween
/:cl:

2024-10-06 22:00 UTC, silicons submitted a review, later dismissed

2024-10-06 22:00 UTC, silicons commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/gammawraith.dm
> +	return
don't need this return

2024-10-06 22:01 UTC, silicons commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/demoncore.dm
> +	AddComponent(/datum/component/horror_aura/)
unnecessary extra / at the end

2024-10-11 19:12 UTC, TheLordME requested changes

2024-10-11 19:12 UTC, TheLordME commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/burning.dm
> +		var/datum/gas_mixture/env = loc.return_air() //Gets all the information on the local air.
this returns the air for the turf, not the whole room (each tile in the room has the same mixture as this one)

2024-10-11 19:12 UTC, TheLordME commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/burning.dm
> +			return
you should not return early without merging removed back into env, or you are creating a vacuum once you are at temperature.

2024-10-11 19:12 UTC, TheLordME commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/burning.dm
> +/mob/living/simple_mob/vore/solarmoth/BiologicalLife(seconds, times_fired)
the comments are misleading and should be revisited

2024-10-11 19:12 UTC, TheLordME commented on code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/demoncore.dm
> +	attack_armor_pen = 50 // Does so little damage already, that this can be justified.
is 8 to 10 really little damage these days?

2024-10-11 21:22 UTC, TheLordME approved these changes

2024-10-12 19:33 UTC, TheLordME approved these changes

2024-10-14 14:38 UTC, merged